import GRDB

// Kotlin cb664b84d 的首次安装基线，不承接 Android Room 历史迁移。
enum Migrations {
    static func migrator() -> DatabaseMigrator {
        var migrator = DatabaseMigrator()
        migrator.registerMigration("v1") { db in
            try db.create(table: "books") { t in
                t.column("bookUrl", .text).notNull().defaults(to: "")
                t.column("tocUrl", .text).notNull().defaults(to: "")
                t.column("origin", .text).notNull().defaults(to: "loc_book")
                t.column("originName", .text).notNull().defaults(to: "")
                t.column("name", .text).notNull().defaults(to: "")
                t.column("author", .text).notNull().defaults(to: "")
                t.column("kind", .text)
                t.column("customTag", .text)
                t.column("coverUrl", .text)
                t.column("customCoverUrl", .text)
                t.column("intro", .text)
                t.column("customIntro", .text)
                t.column("charset", .text)
                t.column("type", .integer).notNull().defaults(to: 0)
                t.column("group", .integer).notNull().defaults(to: 0)
                t.column("latestChapterTitle", .text)
                t.column("latestChapterTime", .integer).notNull().defaults(to: 0)
                t.column("lastCheckTime", .integer).notNull().defaults(to: 0)
                t.column("lastCheckCount", .integer).notNull().defaults(to: 0)
                t.column("totalChapterNum", .integer).notNull().defaults(to: 0)
                t.column("durChapterTitle", .text)
                t.column("durChapterIndex", .integer).notNull().defaults(to: 0)
                t.column("durVolumeIndex", .integer).notNull().defaults(to: 0)
                t.column("chapterInVolumeIndex", .integer).notNull().defaults(to: 0)
                t.column("durChapterPos", .integer).notNull().defaults(to: 0)
                t.column("durChapterTime", .integer).notNull().defaults(to: 0)
                t.column("wordCount", .text)
                t.column("canUpdate", .integer).notNull().defaults(to: 1)
                t.column("order", .integer).notNull().defaults(to: 0)
                t.column("originOrder", .integer).notNull().defaults(to: 0)
                t.column("variable", .text)
                t.column("readConfig", .text)
                t.column("syncTime", .integer).notNull().defaults(to: 0)
                t.column("persistedCoverUrl", .text)
                t.primaryKey(["bookUrl"])
            }
            try db.create(table: "chapters") { t in
                t.column("url", .text).notNull()
                t.column("title", .text).notNull()
                t.column("isVolume", .integer).notNull()
                t.column("baseUrl", .text).notNull()
                t.column("bookUrl", .text).notNull().references("books", column: "bookUrl", onDelete: .cascade)
                t.column("index", .integer).notNull()
                t.column("isVip", .integer).notNull()
                t.column("isPay", .integer).notNull()
                t.column("resourceUrl", .text)
                t.column("tag", .text)
                t.column("wordCount", .text)
                t.column("start", .integer)
                t.column("end", .integer)
                t.column("startFragmentId", .text)
                t.column("endFragmentId", .text)
                t.column("variable", .text)
                t.column("imgUrl", .text)
                t.primaryKey(["url", "bookUrl"])
            }
            try db.create(table: "book_sources") { t in
                t.column("bookSourceUrl", .text).notNull()
                t.column("bookSourceName", .text).notNull()
                t.column("bookSourceGroup", .text)
                t.column("bookSourceType", .integer).notNull()
                t.column("bookUrlPattern", .text)
                t.column("customOrder", .integer).notNull().defaults(to: 0)
                t.column("enabled", .integer).notNull().defaults(to: 1)
                t.column("enabledExplore", .integer).notNull().defaults(to: 1)
                t.column("jsLib", .text)
                t.column("enabledCookieJar", .integer).defaults(to: 0)
                t.column("concurrentRate", .text)
                t.column("header", .text)
                t.column("loginUrl", .text)
                t.column("loginUi", .text)
                t.column("loginCheckJs", .text)
                t.column("coverDecodeJs", .text)
                t.column("bookSourceComment", .text)
                t.column("variableComment", .text)
                t.column("lastUpdateTime", .integer).notNull()
                t.column("respondTime", .integer).notNull()
                t.column("weight", .integer).notNull()
                t.column("exploreUrl", .text)
                t.column("exploreScreen", .text)
                t.column("ruleExplore", .text)
                t.column("searchUrl", .text)
                t.column("ruleSearch", .text)
                t.column("ruleBookInfo", .text)
                t.column("ruleToc", .text)
                t.column("ruleContent", .text)
                t.column("ruleReview", .text)
                t.column("mainJs", .text)
                t.column("eventListener", .integer).notNull().defaults(to: 0)
                t.column("customButton", .integer).notNull().defaults(to: 0)
                t.primaryKey(["bookSourceUrl"])
            }
            try db.create(table: "book_groups") { t in
                t.column("groupId", .integer).notNull()
                t.column("groupName", .text).notNull()
                t.column("cover", .text)
                t.column("order", .integer).notNull()
                t.column("enableRefresh", .integer).notNull().defaults(to: 1)
                t.column("show", .integer).notNull().defaults(to: 1)
                t.column("bookSort", .integer).notNull().defaults(to: -1)
                t.column("onlyUpdateRead", .integer).notNull().defaults(to: 0)
                t.primaryKey(["groupId"])
            }
            try db.create(table: "searchBooks") { t in
                t.column("bookUrl", .text).notNull()
                t.column("origin", .text).notNull().references("book_sources", column: "bookSourceUrl", onDelete: .cascade)
                t.column("originName", .text).notNull()
                t.column("type", .integer).notNull()
                t.column("name", .text).notNull()
                t.column("author", .text).notNull()
                t.column("kind", .text)
                t.column("coverUrl", .text)
                t.column("intro", .text)
                t.column("wordCount", .text)
                t.column("latestChapterTitle", .text)
                t.column("tocUrl", .text).notNull()
                t.column("time", .integer).notNull()
                t.column("variable", .text)
                t.column("originOrder", .integer).notNull()
                t.column("chapterWordCountText", .text)
                t.column("chapterWordCount", .integer).notNull().defaults(to: -1)
                t.column("respondTime", .integer).notNull().defaults(to: -1)
                t.primaryKey(["bookUrl"])
            }
            try db.create(table: "replace_rules") { t in
                t.autoIncrementedPrimaryKey("id")
                t.column("name", .text).notNull().defaults(to: "")
                t.column("group", .text)
                t.column("pattern", .text).notNull().defaults(to: "")
                t.column("replacement", .text).notNull().defaults(to: "")
                t.column("scope", .text)
                t.column("scopeTitle", .integer).notNull().defaults(to: 0)
                t.column("scopeSource", .integer).notNull().defaults(to: 0)
                t.column("scopeContent", .integer).notNull().defaults(to: 1)
                t.column("excludeScope", .text)
                t.column("isEnabled", .integer).notNull().defaults(to: 1)
                t.column("isRegex", .integer).notNull().defaults(to: 1)
                t.column("timeoutMillisecond", .integer).notNull().defaults(to: 3000)
                t.column("sortOrder", .integer).notNull().defaults(to: 0)
            }
            try db.create(table: "cookies") { t in
                t.column("url", .text).notNull()
                t.column("cookie", .text).notNull()
                t.primaryKey(["url"])
            }
            try db.create(table: "readRecord") { t in
                t.column("deviceId", .text).notNull()
                t.column("bookName", .text).notNull()
                t.column("author", .text).notNull().defaults(to: "")
                t.column("readTime", .integer).notNull().defaults(to: 0)
                t.column("lastRead", .integer).notNull().defaults(to: 0)
                t.column("lastChapterTitle", .text)
                t.column("lastChapterIndex", .integer).notNull().defaults(to: -1)
                t.column("lastChapterPos", .integer).notNull().defaults(to: 0)
                t.column("coverUrl", .text)
                t.column("resolvedAuthor", .text)
                t.primaryKey(["deviceId", "bookName", "author"])
            }
            try db.create(table: "bookmarks") { t in
                t.column("time", .integer).notNull()
                t.column("bookName", .text).notNull()
                t.column("bookAuthor", .text).notNull()
                t.column("chapterIndex", .integer).notNull()
                t.column("chapterPos", .integer).notNull()
                t.column("chapterName", .text).notNull()
                t.column("bookText", .text).notNull()
                t.column("content", .text).notNull()
                t.primaryKey(["time"])
            }
            try db.create(index: "index_books_name_author", on: "books", columns: ["name", "author"], unique: true)
            try db.create(index: "index_chapters_bookUrl", on: "chapters", columns: ["bookUrl"], unique: false)
            try db.create(index: "index_chapters_bookUrl_index", on: "chapters", columns: ["bookUrl", "index"], unique: true)
            try db.create(index: "index_book_sources_bookSourceUrl", on: "book_sources", columns: ["bookSourceUrl"], unique: false)
            try db.create(index: "index_searchBooks_bookUrl", on: "searchBooks", columns: ["bookUrl"], unique: true)
            try db.create(index: "index_searchBooks_origin", on: "searchBooks", columns: ["origin"], unique: false)
            try db.create(index: "index_replace_rules_id", on: "replace_rules", columns: ["id"], unique: false)
            try db.create(index: "index_cookies_url", on: "cookies", columns: ["url"], unique: true)
            try db.create(index: "index_bookmarks_bookName_bookAuthor", on: "bookmarks", columns: ["bookName", "bookAuthor"], unique: false)
            try db.execute(sql: "CREATE INDEX index_readRecord_snapshot ON readRecord(bookName, author, lastRead DESC, deviceId, resolvedAuthor)")
        }
        migrator.registerMigration("v2") { db in
            try db.create(table: "txtTocRules") { t in
                t.primaryKey("id", .integer)
                t.column("name", .text).notNull()
                t.column("rule", .text).notNull()
                t.column("replacement", .text).notNull().defaults(to: "")
                t.column("example", .text)
                t.column("serialNumber", .integer).notNull()
                t.column("enable", .boolean).notNull()
            }
            for rule in TxtTocRule.builtIn { try rule.insert(db) }
        }
        SourceLoginMigration.register(in: &migrator)
        HttpTTSMigration.register(in: &migrator)
        DictRuleMigration.register(in: &migrator)
        ReaderMigration.register(in: &migrator)
        RssMigration.register(in: &migrator)
        EntityCompatibilityMigration.register(in: &migrator)
        WebPreviewMigration.register(in: &migrator)
        return migrator

    }
}
