import GRDB

enum RssMigration {
    static func register(in migrator: inout DatabaseMigrator) {
        migrator.registerMigration("v6") { db in
            try db.create(table: RssSource.databaseTableName) { t in
                t.column("sourceUrl", .text).notNull().defaults(to: "")
                t.column("sourceName", .text).notNull().defaults(to: "")
                t.column("sourceIcon", .text).notNull().defaults(to: "")
                t.column("sourceGroup", .text)
                t.column("sourceComment", .text)
                t.column("enabled", .integer).notNull().defaults(to: true)
                t.column("variableComment", .text)
                t.column("jsLib", .text)
                t.column("enabledCookieJar", .integer)
                t.column("concurrentRate", .text)
                t.column("header", .text)
                t.column("loginUrl", .text)
                t.column("loginUi", .text)
                t.column("loginCheckJs", .text)
                t.column("coverDecodeJs", .text)
                t.column("sortUrl", .text)
                t.column("singleUrl", .integer).notNull().defaults(to: false)
                t.column("articleStyle", .integer).notNull().defaults(to: 0)
                t.column("ruleArticles", .text)
                t.column("ruleNextPage", .text)
                t.column("ruleTitle", .text)
                t.column("rulePubDate", .text)
                t.column("ruleDescription", .text)
                t.column("ruleImage", .text)
                t.column("ruleLink", .text)
                t.column("ruleContent", .text)
                t.column("nextContentUrl", .text)
                t.column("contentWhitelist", .text)
                t.column("contentBlacklist", .text)
                t.column("shouldOverrideUrlLoading", .text)
                t.column("style", .text)
                t.column("enableJs", .integer).notNull().defaults(to: true)
                t.column("loadWithBaseUrl", .integer).notNull().defaults(to: true)
                t.column("injectJs", .text)
                t.column("preloadJs", .text)
                t.column("startHtml", .text)
                t.column("startStyle", .text)
                t.column("startJs", .text)
                t.column("showWebLog", .integer).notNull().defaults(to: false)
                t.column("lastUpdateTime", .integer).notNull().defaults(to: 0)
                t.column("customOrder", .integer).notNull().defaults(to: 0)
                t.column("type", .integer).notNull().defaults(to: 0)
                t.column("preload", .integer).notNull().defaults(to: false)
                t.column("cacheFirst", .integer).notNull().defaults(to: false)
                t.column("searchUrl", .text)
                t.primaryKey(["sourceUrl"])
            }
            try db.create(table: RssArticle.databaseTableName) { t in
                t.column("origin", .text).notNull().defaults(to: "")
                t.column("sort", .text).notNull().defaults(to: "")
                t.column("title", .text).notNull().defaults(to: "")
                t.column("order", .integer).notNull().defaults(to: 0)
                t.column("link", .text).notNull().defaults(to: "")
                t.column("pubDate", .text)
                t.column("description", .text)
                t.column("content", .text)
                t.column("image", .text)
                t.column("group", .text).notNull().defaults(to: "默认分组")
                t.column("read", .integer).notNull().defaults(to: false)
                t.column("variable", .text)
                t.column("type", .integer).notNull().defaults(to: 0)
                t.column("durPos", .integer).notNull().defaults(to: 0)
                t.primaryKey(["origin", "link", "sort"])
            }
            try db.create(table: RssStar.databaseTableName) { t in
                t.column("origin", .text).notNull().defaults(to: "")
                t.column("sort", .text).notNull().defaults(to: "")
                t.column("title", .text).notNull().defaults(to: "")
                t.column("starTime", .integer).notNull().defaults(to: 0)
                t.column("link", .text).notNull().defaults(to: "")
                t.column("pubDate", .text)
                t.column("description", .text)
                t.column("content", .text)
                t.column("image", .text)
                t.column("group", .text).notNull().defaults(to: "默认分组")
                t.column("variable", .text)
                t.column("type", .integer).notNull().defaults(to: 0)
                t.column("durPos", .integer).notNull().defaults(to: 0)
                t.primaryKey(["origin", "link"])
            }
            try db.create(table: RssReadRecord.databaseTableName) { t in
                t.column("record", .text).notNull().defaults(to: "")
                t.column("title", .text)
                t.column("readTime", .integer)
                t.column("read", .integer).notNull().defaults(to: true)
                t.column("origin", .text).notNull().defaults(to: "")
                t.column("sort", .text).notNull().defaults(to: "")
                t.column("image", .text)
                t.column("type", .integer).notNull().defaults(to: 0)
                t.column("durPos", .integer).notNull().defaults(to: 0)
                t.column("pubDate", .text)
                t.primaryKey(["record"])
            }
        }
    }
}
