// swift-tools-version: 6.1
import PackageDescription

let package = Package(
    name: "AppCoreCheck",
    platforms: [.macOS(.v14)],
    dependencies: [.package(path: "../../Packages/LegadoCore")],
    targets: [
        .testTarget(name: "AppPreferencesCheckTests", dependencies: ["SettingsBackupCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .target(name: "RssCheck", dependencies: [.product(name: "LegadoCore", package: "LegadoCore")],
                swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "RssCheckTests", dependencies: ["RssCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "BackupExportCheckTests", dependencies: ["SettingsBackupCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .target(name: "MediaCheck", dependencies: [.product(name: "LegadoCore", package: "LegadoCore")],
                swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "MediaCheckTests", dependencies: ["MediaCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .target(name: "WebServiceCheck", dependencies: [.product(name: "LegadoCore", package: "LegadoCore")], swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "WebServiceCheckTests", dependencies: ["WebServiceCheck"], swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "ReaderAdvancedCheckTests", dependencies: ["ReaderCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .target(name: "BookshelfAdvancedCheck", dependencies: [.product(name: "LegadoCore", package: "LegadoCore")],
                swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "BookshelfAdvancedCheckTests", dependencies: ["BookshelfAdvancedCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .target(name: "SourceEditCheck", dependencies: [.product(name: "LegadoCore", package: "LegadoCore")],
                swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "SourceEditCheckTests", dependencies: ["SourceEditCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "MobiImportCheckTests", dependencies: ["LocalImportCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .target(name: "BrowserCheck", swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "BrowserCheckTests", dependencies: ["BrowserCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .target(name: "ReadAloudCheck", swiftSettings: [.swiftLanguageMode(.v5)]),
        .target(name: "ReadAloudAudioCheck", dependencies: [.product(name: "LegadoCore", package: "LegadoCore")],
                swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "ReadAloudCheckTests", dependencies: ["ReadAloudCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .target(name: "JsSourceCheck", dependencies: [.product(name: "LegadoCore", package: "LegadoCore")],
                swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "JsSourceCheckTests", dependencies: ["JsSourceCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "SourceLoginReviewCoreTests", dependencies: [.product(name: "LegadoCore", package: "LegadoCore")],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .target(name: "SourceLoginCheck", dependencies: [.product(name: "LegadoCore", package: "LegadoCore")],
                swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "SourceLoginCheckTests", dependencies: ["SourceLoginCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .target(name: "LocalImportCheck", dependencies: [.product(name: "LegadoCore", package: "LegadoCore")],
                swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "LocalImportCheckTests", dependencies: ["LocalImportCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .target(name: "ExploreImagesCheck", dependencies: [.product(name: "LegadoCore", package: "LegadoCore")],
                swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "ExploreImagesCheckTests", dependencies: ["ExploreImagesCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .target(name: "ReaderCheck", dependencies: [.product(name: "LegadoCore", package: "LegadoCore")],
                swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "ReaderCheckTests", dependencies: ["ReaderCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .target(name: "SettingsBackupCheck", dependencies: [.product(name: "LegadoCore", package: "LegadoCore")],
                swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "SettingsBackupCheckTests", dependencies: ["SettingsBackupCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .target(name: "DatabaseLifecycleCheck", swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "DatabaseLifecycleCheckTests", dependencies: ["DatabaseLifecycleCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .target(name: "AppCoreCheck", dependencies: [.product(name: "LegadoCore", package: "LegadoCore")],
                swiftSettings: [.swiftLanguageMode(.v5)]),
        .target(name: "EntitySettingsCheck", dependencies: [.product(name: "LegadoCore", package: "LegadoCore")],
                swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "EntitySettingsCheckTests", dependencies: ["EntitySettingsCheck", "AppCoreCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)]),
        .testTarget(name: "AppCoreCheckTests", dependencies: ["AppCoreCheck"],
                    swiftSettings: [.swiftLanguageMode(.v5)])
    ]
)
